name: Deploy Panel Roque

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy with ssh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.9'
          extensions: ctype, dom, fileinfo, filter, hash, openssl, pcre, pdo, session, tokenizer, mbstring, xml, curl, json, mysql

      - name: Set up NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      - name: Test
        run: ls -la

      - name: Configure environment
        run: cp .env.example .env && php artisan key:generate && php artisan storage:link

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Build assets with npm
        run: npm install --save-dev vite laravel-vite-plugin && npm run build

      - name: Prepare deploy directory
        run: |
          zip -r release.zip ./
          mkdir -p release

      - name: Transfer files via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "release.zip"
          target: ${{ vars.RELEASE_DIR }}

      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ vars.APP_DIR }}
            docker compose -f ./docker-compose.prod.yml down
            rm * -rf
            cd ${{ vars.RELEASE_DIR }}
            unzip -o release.zip -d ${{ vars.APP_DIR }}
            cp .env ${{ vars.APP_DIR }}
            rm -rf release.zip
            cd ${{ vars.APP_DIR }}
            chown -R www-data:www-data .
            docker compose -f ./docker-compose.prod.yml up -d --build

      - name: Clean up local files
        run: rm -rf release.zip release
